ALTER TABLE "tasks" ADD COLUMN "task_key" text;
ALTER TABLE "tasks" ADD COLUMN "acceptance_criteria" text;
ALTER TABLE "tasks" ADD COLUMN "blocked_by_text" text;
ALTER TABLE "tasks" ADD COLUMN "due_date" date;
ALTER TABLE "tasks" ADD COLUMN "layer" text;
ALTER TABLE "tasks" ADD COLUMN "module" text;
ALTER TABLE "tasks" ADD COLUMN "repo_path" text;
ALTER TABLE "tasks" ADD COLUMN "risk_level" text;
ALTER TABLE "tasks" ADD COLUMN "sprint_phase" text;
ALTER TABLE "tasks" ADD COLUMN "task_type" text;
ALTER TABLE "tasks" ADD COLUMN "route_mode" text;
ALTER TABLE "tasks" ADD COLUMN "req_id" text;
ALTER TABLE "tasks" ADD COLUMN "pr_state" text;
ALTER TABLE "tasks" ADD COLUMN "pr_url" text;
ALTER TABLE "tasks" ADD COLUMN "agent_confidence_level" text;
ALTER TABLE "tasks" ADD COLUMN "notion_properties" jsonb;
ALTER TABLE "tasks" ADD COLUMN "notion_relations" jsonb;
CREATE INDEX "tasks_company_task_key_idx" ON "tasks" USING btree ("company_id","task_key");
CREATE INDEX "tasks_company_route_mode_idx" ON "tasks" USING btree ("company_id","route_mode");
CREATE INDEX "tasks_company_req_id_idx" ON "tasks" USING btree ("company_id","req_id");
CREATE INDEX "tasks_company_pr_state_idx" ON "tasks" USING btree ("company_id","pr_state");
