import { randomUUID } from "node:crypto";
import { definePlugin, runWorker, type PluginApiRequestInput } from "@paperclipai/plugin-sdk";

type SmokeInput = {
  companyId: string;
  taskId: string;
  assigneeAgentId?: string | null;
  actorAgentId?: string | null;
  actorUserId?: string | null;
  actorRunId?: string | null;
};

type SmokeSummary = {
  rootTaskId: string;
  childTaskId: string | null;
  blockerTaskId: string | null;
  billingCode: string;
  joinedRows: unknown[];
  subtreeTaskIds: string[];
  wakeupQueued: boolean;
};

let readSmokeSummary: ((companyId: string, taskId: string) => Promise<SmokeSummary | null>) | null = null;
let initializeSmoke: ((input: SmokeInput) => Promise<SmokeSummary>) | null = null;

function tableName(namespace: string) {
  return `${namespace}.smoke_runs`;
}

function stringField(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value : null;
}

const plugin = definePlugin({
  async setup(ctx) {
    readSmokeSummary = async function readSummary(companyId: string, taskId: string): Promise<SmokeSummary | null> {
      const rows = await ctx.db.query<{
        root_task_id: string;
        child_task_id: string | null;
        blocker_task_id: string | null;
        billing_code: string;
        task_title: string;
        last_summary: unknown;
      }>(
        `SELECT s.root_task_id, s.child_task_id, s.blocker_task_id, s.billing_code, i.title AS task_title, s.last_summary
         FROM ${tableName(ctx.db.namespace)} s
         JOIN public.tasks i ON i.id = s.root_task_id
         WHERE s.root_task_id = $1`,
        [taskId],
      );
      const row = rows[0];
      if (!row) return null;
      const orchestration = await ctx.tasks.summaries.getOrchestration({
        taskId,
        companyId,
        includeSubtree: true,
        billingCode: row.billing_code,
      });
      return {
        rootTaskId: row.root_task_id,
        childTaskId: row.child_task_id,
        blockerTaskId: row.blocker_task_id,
        billingCode: row.billing_code,
        joinedRows: rows,
        subtreeTaskIds: orchestration.subtreeTaskIds,
        wakeupQueued: Boolean((row.last_summary as { wakeupQueued?: unknown } | null)?.wakeupQueued),
      };
    };

    initializeSmoke = async function runSmoke(input: SmokeInput): Promise<SmokeSummary> {
      const root = await ctx.tasks.get(input.taskId, input.companyId);
      if (!root) throw new Error(`Task not found: ${input.taskId}`);

      const billingCode = `plugin-smoke:${input.taskId}`;
      const actor = {
        actorAgentId: input.actorAgentId ?? null,
        actorUserId: input.actorUserId ?? null,
        actorRunId: input.actorRunId ?? null,
      };
      const blocker = await ctx.tasks.create({
        companyId: input.companyId,
        parentId: input.taskId,
        inheritExecutionWorkspaceFromTaskId: input.taskId,
        title: "Orchestration smoke blocker",
        description: "Resolved blocker used to verify plugin relation writes without preventing the smoke wakeup.",
        status: "done",
        priority: "low",
        billingCode,
        originKind: `plugin:${ctx.manifest.id}:blocker`,
        originId: `${input.taskId}:blocker`,
        actor,
      });

      const child = await ctx.tasks.create({
        companyId: input.companyId,
        parentId: input.taskId,
        inheritExecutionWorkspaceFromTaskId: input.taskId,
        title: "Orchestration smoke child",
        description: "Generated by the orchestration smoke plugin to verify task, document, relation, wakeup, and summary APIs.",
        status: "todo",
        priority: "medium",
        assigneeAgentId: input.assigneeAgentId ?? root.assigneeAgentId ?? undefined,
        billingCode,
        originKind: `plugin:${ctx.manifest.id}:child`,
        originId: `${input.taskId}:child`,
        blockedByTaskIds: [blocker.id],
        actor,
      });

      await ctx.tasks.relations.setBlockedBy(child.id, [blocker.id], input.companyId, actor);
      await ctx.tasks.documents.upsert({
        taskId: child.id,
        companyId: input.companyId,
        key: "orchestration-smoke",
        title: "Orchestration Smoke",
        format: "markdown",
        body: [
          "# Orchestration Smoke",
          "",
          `- Root task: ${input.taskId}`,
          `- Child task: ${child.id}`,
          `- Billing code: ${billingCode}`,
        ].join("\n"),
        changeSummary: "Recorded orchestration smoke output",
      });

      const wakeup = await ctx.tasks.requestWakeup(child.id, input.companyId, {
        reason: "plugin:orchestration_smoke",
        contextSource: "plugin-orchestration-smoke",
        idempotencyKey: `${input.taskId}:child`,
        ...actor,
      });
      const orchestration = await ctx.tasks.summaries.getOrchestration({
        taskId: input.taskId,
        companyId: input.companyId,
        includeSubtree: true,
        billingCode,
      });
      const summarySnapshot = {
        childTaskId: child.id,
        blockerTaskId: blocker.id,
        wakeupQueued: wakeup.queued,
        subtreeTaskIds: orchestration.subtreeTaskIds,
      };

      await ctx.db.execute(
        `INSERT INTO ${tableName(ctx.db.namespace)} (id, root_task_id, child_task_id, blocker_task_id, billing_code, last_summary)
         VALUES ($1, $2, $3, $4, $5, $6::jsonb)
         ON CONFLICT (id) DO UPDATE SET
           child_task_id = EXCLUDED.child_task_id,
           blocker_task_id = EXCLUDED.blocker_task_id,
           billing_code = EXCLUDED.billing_code,
           last_summary = EXCLUDED.last_summary,
           updated_at = now()`,
        [
          randomUUID(),
          input.taskId,
          child.id,
          blocker.id,
          billingCode,
          JSON.stringify(summarySnapshot),
        ],
      );

      return {
        rootTaskId: input.taskId,
        childTaskId: child.id,
        blockerTaskId: blocker.id,
        billingCode,
        joinedRows: await ctx.db.query(
          `SELECT s.id, s.billing_code, i.title AS root_title
           FROM ${tableName(ctx.db.namespace)} s
           JOIN public.tasks i ON i.id = s.root_task_id
           WHERE s.root_task_id = $1`,
          [input.taskId],
        ),
        subtreeTaskIds: orchestration.subtreeTaskIds,
        wakeupQueued: wakeup.queued,
      };
    };

    ctx.data.register("surface-status", async (params) => {
      const companyId = stringField(params.companyId);
      const taskId = stringField(params.taskId);
      return {
        status: "ok",
        checkedAt: new Date().toISOString(),
        databaseNamespace: ctx.db.namespace,
        routeKeys: (ctx.manifest.apiRoutes ?? []).map((route) => route.routeKey),
        capabilities: ctx.manifest.capabilities,
        summary: companyId && taskId ? await readSmokeSummary?.(companyId, taskId) ?? null : null,
      };
    });

    ctx.actions.register("initialize-smoke", async (params) => {
      const companyId = stringField(params.companyId);
      const taskId = stringField(params.taskId);
      if (!companyId || !taskId) throw new Error("companyId and taskId are required");
      if (!initializeSmoke) throw new Error("Smoke initializer is not ready");
      return initializeSmoke({
        companyId,
        taskId,
        assigneeAgentId: stringField(params.assigneeAgentId),
        actorAgentId: stringField(params.actorAgentId),
        actorUserId: stringField(params.actorUserId),
        actorRunId: stringField(params.actorRunId),
      });
    });
  },

  async onApiRequest(input: PluginApiRequestInput) {
    if (input.routeKey === "summary") {
      const taskId = input.params.taskId;
      return {
        body: await readSmokeSummary?.(input.companyId, taskId) ?? null,
      };
    }

    if (input.routeKey === "initialize") {
      if (!initializeSmoke) throw new Error("Smoke initializer is not ready");
      const body = input.body as Record<string, unknown> | null;
      return {
        status: 201,
        body: await initializeSmoke({
          companyId: input.companyId,
          taskId: input.params.taskId,
          assigneeAgentId: stringField(body?.assigneeAgentId),
          actorAgentId: input.actor.agentId ?? null,
          actorUserId: input.actor.userId ?? null,
          actorRunId: input.actor.runId ?? null,
        }),
      };
    }

    return {
      status: 404,
      body: { error: `Unknown orchestration smoke route: ${input.routeKey}` },
    };
  },

  async onHealth() {
    return {
      status: "ok",
      message: "Orchestration smoke plugin worker is running",
      details: {
        surfaces: ["database", "scoped-api-route", "task-panel", "orchestration-apis"],
      },
    };
  }
});

export default plugin;
runWorker(plugin, import.meta.url);
